### ISSUE TITLE
Seeding fails with error

### ISSUE THREAD

**Issue by SerdoSchofield** [BYU-TRG-Team/js-qt21-scorecard#19]
Running `node server/seed.js` fails with the following error after commit 96d4973b956cc959e549e9f0fc393f8bf3a777d3.

(node:196826) UnhandledPromiseRejectionWarning: error: relation "roles" does not exist
    at Parser.parseErrorMessage (/home/trg/scorecard/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/trg/scorecard/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/trg/scorecard/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.stream.on (/home/trg/scorecard/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:196826) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:196826) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Andrew-Dame** [comment]
Thanks for reporting this! Resolved in [v3.2.2](https://github.com/BYU-TRG-Team/scorecard/releases/tag/v3.2.2)
